# This is a basic workflow to help you get started with Actions
name: Blog deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ hexo ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: ðŸ¤” Checkout source
        uses: actions/checkout@v1
        with:
            ref: master

      - name: ðŸŽ‰ Setup Node.js
        uses: actions/setup-node@v1
        with:
              node-version: '12'


      - name: ðŸšš Setup Hexo
        env: 
                # HEXO_DEPLOY_PRI_XIAOXIN_WINDOW è¿™ä¸ªå°±æ˜¯é…ç½®hexoä»“åº“secretsçš„nameï¼Œä¸€å®šè¦å¯¹åº”ä¸Š
                ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
                    mkdir -p ~/.ssh/
                    echo "$DEPLOY_KEY"> ~/.ssh/id_rsa
                    chmod 700 ~/.ssh
                    chmod 600 ~/.ssh/id_rsa
                    ssh-keyscan github.com >> ~/.ssh/known_hosts
                    git config --global user.email "chzaaow@gmail.com"
                    git config --global user.name "m1ria"
                    npm install hexo-cli -g
                    npm install
      - name: ðŸ“‚ Deploy
        run: |
            hexo init
            hexo clean
            hexo generate
            hexo deploy